name: Chat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.5.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  firebase_database: ^10.1.1
  firebase_messaging: ^14.4.1
  http: ^0.13.5
  flutter_local_notifications: ^13.0.0
  elegant_notification: ^1.8.1
  url_launcher: ^6.1.10
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true